CREATE TYPE post_type_category AS ENUM (
    'music',
    'podcast',
    'reflection',
    'event',
    'book'
);

CREATE TABLE uplift_posts(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES uplift_users(id) ON DELETE CASCADE NOT NULL,
    title TEXT,
    link TEXT,
    event_dates TEXT,
    by TEXT,
    content TEXT,
    post_type post_type_category NOT NULL,
    date_created TIMESTAMPTZ NOT NULL DEFAULT now()
)